@startuml

title 睡眠改善

hide empty members
skinparam class {
  BackgroundColor<<deprecated>> Grey
  BackgroundColor<<done>> Cyan
  BackgroundColor<<new>> Yellow
}

left to right direction


package 勝利条件 {
  class 眠りが理想的である
}

package 中間目的 {
  class 寝付きがよい
  寝付きがよい --> 眠りが理想的である

  class 寝起きがよい
  寝起きがよい --> 眠りが理想的である

  class 朝の始業前定期タスクを欠かさずできる
  朝の始業前定期タスクを欠かさずできる -> 寝起きがよい

  class 日中眠くならない
  note bottom: 施策がない
  日中眠くならない --> 眠りが理想的である

  class 二度寝しない<<new>>
  二度寝しない -> 朝の始業前定期タスクを欠かさずできる

  class 覚醒後布団から脱出できる
  note bottom
  覚醒後「すぐに」出られないとあまり意味がないのと
  トイレから戻ってきて寒くて布団に逆戻りしてしまった
  end note
  覚醒後布団から脱出できる -> 二度寝しない

  class 布団に後戻りせずにすむ
  note bottom
  寒いと戻って温まりたくなる
  二度寝のリスクが跳ね上がる
  end note
  布団に後戻りせずにすむ -> 二度寝しない

  class 朝起きて膝が痛くない<<new>>
  note bottom
  今朝、膝を布団で温めたいと感じた
  「もう少し寝たい」ではなかった
  end note
  朝起きて膝が痛くない -> 覚醒後布団から脱出できる

  class 朝起きて腰が痛くない<<new>>
  朝起きて腰が痛くない -> 覚醒後布団から脱出できる
}

package 施策 {
  class 寝る前に腹を減らさない
  寝る前に腹を減らさない --> 寝付きがよい
  寝る前に腹を減らさない --> 寝起きがよい
  寝る3_4時間前に豚肉を食べる -> 寝る前に腹を減らさない
  緊急用軽食を常備する -> 寝る前に腹を減らさない

  class 布団脱出時に毛布をベッドから落として冷ます
  note bottom
  消極的だが、ベッドに戻っても暖かくなくて意味がない環境をつくる
  end note
  布団脱出時に毛布をベッドから落として冷ます --> 布団に後戻りせずにすむ

  class 膝のストレッチ<<new>>
  膝のストレッチ --> 朝起きて膝が痛くない

  class 布団の中で作業する<<new>>
  note bottom
  例えば読書

  頭が覚醒してそのままきれいに起きられそうな反面
  二度寝のリスクもある
  end note
  布団の中で作業する --> 朝の始業前定期タスクを欠かさずできる

  class 姿勢よく寝る<<new>>
  note bottom
  - 膝を曲げて寝ると朝膝が痛くなる
  - 横向きに寝ると骨盤が嫌な感じになる
  end note
  姿勢よく寝る --> 朝起きて膝が痛くない
  姿勢よく寝る --> 朝起きて腰が痛くない

  class よい寝具を買う<<new>>
  note bottom
  高価なのと、物件備え付けの寝具を処分できないのがネック
  end note
  よい寝具を買う --> 朝起きて膝が痛くない
  よい寝具を買う --> 朝起きて腰が痛くない

  class 7_5時間逆算して就寝する
  note bottom
  要するに早寝
  元も子もないが効果的
  end note
  7_5時間逆算して就寝する --> 寝起きがよい
}

package 廟算八要素 {
  class メンバー {
   + 自分
  }
  class 予算規模 {
   + ...
  }
  class 納期 {
   + ...
  }
  class ビジネスモデル {
   + ...
  }
  class 環境 {
   + kindle
   + サウナ
   + 乾燥
   + 寒い
   + スヌーズ
   -- エアコンの知見 --
   タオルの乾燥時間条件(1h程度)
   フィルタ掃除を怠ると空気の乾燥感が増す
   -- 寝具 --
   物件備え付けベッド
   物件備え付けマットレス
  }

  class 競合 {
   + ...
  }
  class 外敵 {
   + ...
  }
  class 問題 {
   + 自律神経が壊れる
   + 朝起きると膝が痛い
  }
  note right of 問題::自律神経が壊れる
  定期的にサウナに通って立て直している
  end note
  note right of 問題::朝起きると膝が痛い
  二度寝の根本原因な気がする

  「寝たい」わけではなく、
  経験則上二度寝して温めると収まる
  end note
}

中間目的 --u[hidden]--> 勝利条件
施策 --u[hidden]--> 中間目的
廟算八要素 ---u[hidden]--> 施策

@enduml
