@startuml

title 睡眠改善

hide empty members
skinparam class {
  BackgroundColor<<deprecated>> Grey
  BackgroundColor<<done>> Cyan
  BackgroundColor<<new>> Yellow
}

left to right direction


package 勝利条件 {
  class 眠りが理想的である
}

package 中間目的 {
  class 寝付きが良い
  寝付きが良い --> 眠りが理想的である

  class 寝起きがよい
  寝起きがよい --> 眠りが理想的である

  class 日中眠くならない
  日中眠くならない --> 眠りが理想的である

  class 覚醒後布団から脱出できる
  朝の始業前定期タスクを欠かさずできる -> 寝起きがよい

  class 朝の始業前定期タスクを欠かさずできる
  note bottom
  矢印を逆にした。
  朝の定期タスクをできることを「寝起きがよい」ことの定義とする
  end note
  覚醒後布団から脱出できる -> 朝の始業前定期タスクを欠かさずできる
}

package 施策 {
  class 睡眠の質を改善する
  睡眠の質を改善する --> 寝起きがよい
  睡眠の質を改善する --> 日中眠くならない

  class 布団に入ったらスマホではなくkindleを見る
  布団に入ったらスマホではなくkindleを見る -> 睡眠の質を改善する

  class 寝る前に腹を減らさない
  寝る前に腹を減らさない --> 寝付きが良い
  寝る前に腹を減らさない --> 寝起きがよい
  寝る3_4時間前に豚肉を食べる -> 寝る前に腹を減らさない

  class 朝一番にやることを目覚ましで読み上げる
  note bottom
  いまいち起きられなくなってきた
  緊急性が低いと普通に二度寝しちゃう
  end note
  朝一番にやることを目覚ましで読み上げる --> 覚醒後布団から脱出できる

  class アラーム音をうるさいものに変える<<done>>
  note bottom
  聞こえた。読み上げ音声もかき消されることなく一応聞こえるのでこれでいく
  end note
  アラーム音をうるさいものに変える -> 朝一番にやることを目覚ましで読み上げる

  class 朝食を前日のうちに仕込んでおく
  note bottom
  朝寝起きの頭で覚えてないのでこれも読み上げ必要
  end note
  朝食を前日のうちに仕込んでおく --> 覚醒後布団から脱出できる

  class フレンチトーストを仕込む<<done>>
  note bottom
  美味しく作れるようになった
  朝起きる楽しみとして機能しそう！
  end note
  フレンチトーストを仕込む -> 朝食を前日のうちに仕込んでおく
}

package 廟算八要素 {
  class メンバー {
   + 自分
  }
  class 予算規模 {
   + ...
  }
  class 納期 {
   + ...
  }
  class ビジネスモデル {
   + ...
  }
  class 環境 {
   + kindle
   + サウナ
  }

  class 競合 {
   + ...
  }
  class 外敵 {
   + ...
  }
  class 問題 {
   + 自律神経が壊れる
  }
  note right of 問題::自律神経が壊れる
  定期的にサウナに通って立て直している
  end note
}

中間目的 --u[hidden]--> 勝利条件
施策 --u[hidden]--> 中間目的
廟算八要素 ---u[hidden]--> 施策

@enduml
