@startuml

title 睡眠改善

hide empty members
skinparam class {
  BackgroundColor<<deprecated>> Grey
  BackgroundColor<<done>> Cyan
  BackgroundColor<<new>> Yellow
}

left to right direction


package 勝利条件 {
  class 眠りが理想的である
}

package 中間目的 {
  class 寝付きがよい
  寝付きがよい --> 眠りが理想的である

  class 寝起きがよい
  寝起きがよい --> 眠りが理想的である

  class 日中眠くならない
  日中眠くならない --> 眠りが理想的である

  class 覚醒後布団から脱出できる
  朝の始業前定期タスクを欠かさずできる -> 寝起きがよい

  class 朝の始業前定期タスクを欠かさずできる
  note bottom
  矢印を逆にした。
  朝の定期タスクをできることを「寝起きがよい」ことの定義とする
  end note
  覚醒後布団から脱出できる -> 朝の始業前定期タスクを欠かさずできる
}

package 施策 {
  class 睡眠の質を改善する
  睡眠の質を改善する --> 寝起きがよい
  睡眠の質を改善する --> 日中眠くならない

  class 布団に入ったらスマホではなくkindleを見る
  布団に入ったらスマホではなくkindleを見る -> 睡眠の質を改善する

  class 寝る前に水を飲みすぎない<<new>>
  note bottom
  尿意で朝2時に目が覚めてしまった
  end note
  寝る前に水を飲みすぎない -> 睡眠の質を改善する

  class 睡眠中の体温を上げる<<new>>
  note bottom
  朝動けないくらい寒いのに
  良質な睡眠をとれているわけがない
  end note
  睡眠中の体温を上げる -> 睡眠の質を改善する

  class 着る毛布を買う<<new>>
  note bottom
  起床成功の要因にはならないかもしれないが、
  現状日中帯も寒くて毛布をかぶって仕事しているので無駄にはならない
  end note
  着る毛布を買う -> 睡眠中の体温を上げる

  class 寝る前に腹を減らさない
  寝る前に腹を減らさない --> 寝付きがよい
  寝る前に腹を減らさない --> 寝起きがよい
  寝る3_4時間前に豚肉を食べる -> 寝る前に腹を減らさない

  class 朝一番にやりたいことを目覚ましで読み上げる<<new>>
  note "例えば「フレンチトースト焼く!」とか" as todo_example
  朝一番にやりたいことを目覚ましで読み上げる - todo_example
  朝一番にやりたいことを目覚ましで読み上げる --> 覚醒後布団から脱出できる

  class 朝一番にやらなくていいことを読み上げない<<new>>
  note bottom
  起きてタスクリストを開きさえすれば勝ち
  (億劫でなければあとは「やる」ので)
  起きるのに最低限のものだけ読み上げる
  end note
  朝一番にやらなくていいことを読み上げない --> 覚醒後布団から脱出できる

  class 朝食を前日のうちに仕込んでおく
  朝食を前日のうちに仕込んでおく --> 覚醒後布団から脱出できる
  朝食を前日のうちに仕込んでおく - todo_example

  class スヌーズやめる<<new>>
  note bottom
  スヌーズをかけてしまうと思考が麻痺して、
  本当に緊急になるまで布団を脱出できなくなる
  - 業務開始時間
  - 尿意/便意
  - 空腹
  end note
  スヌーズやめる --> 覚醒後布団から脱出できる
}

package 廟算八要素 {
  class メンバー {
   + 自分
  }
  class 予算規模 {
   + ...
  }
  class 納期 {
   + ...
  }
  class ビジネスモデル {
   + ...
  }
  class 環境 {
   + kindle
   + サウナ
   + 乾燥
   + 寒い
   + スヌーズ
  }

  class 競合 {
   + ...
  }
  class 外敵 {
   + ...
  }
  class 問題 {
   + 自律神経が壊れる
  }
  note right of 問題::自律神経が壊れる
  定期的にサウナに通って立て直している
  end note
}

中間目的 --u[hidden]--> 勝利条件
施策 --u[hidden]--> 中間目的
廟算八要素 ---u[hidden]--> 施策

@enduml
