@startuml

title 人生

hide empty members
skinparam class {
  BackgroundColor<<deprecated>> Grey
  BackgroundColor<<done>> Cyan
  BackgroundColor<<new>> Yellow
}


package 勝利条件 {
  class 幸せに生きる
}

package 中間目的 {
  class 不安がない
  不安がない --> 幸せに生きる

  class キャリアの不安がない<<ref>> extends 不安がない
  class お金の不安がない extends 不安がない

  class 自己虐待をしていない
  自己虐待をしていない --> 幸せに生きる

  class 他者との認識違いがない
  他者との認識違いがない --> 幸せに生きる
}

package 施策 {
  class 自己虐待を見つけて改善する
  自己虐待を見つけて改善する --> 自己虐待をしていない

  class 人生をプ譜に書き留める
  人生をプ譜に書き留める --> 自己虐待を見つけて改善する

  class 自分の考えを相手が理解し相手の考えを自分が理解していることを確認する
  自分の考えを相手が理解し相手の考えを自分が理解していることを確認する --> 他者との認識違いがない

  class 自分の考えを自分が理解していることを確認する
  自分の考えを自分が理解していることを確認する --> 自己虐待をしていない

  class プ譜をplantumlとJetBrainsで描く<<done>>
  note bottom: いい感じ！継続
  プ譜をplantumlとJetBrainsで描く --> 自己虐待をしていない

  class 寝る前に明日の朝食としてフレンチトーストを仕込む<<deprecated>>
  note bottom
  あまり美味しくないのでもうやらない
  前の日のうちに翌日の朝食の献立を組み立てておくというのは
  朝起きる上で効果があった
  end note
  寝る前に明日の朝食としてフレンチトーストを仕込む --> 自己虐待をしていない

  class 食事をアプリで管理する<<deprecated>>
  note bottom
   言うほど健康的に太れない
   あと目的を忘れてた
  end note
}

package 廟算八要素 {
  class メンバー {
   + 自分
   + 個人事業の営業代行
   + アサイン先正社員
   + 友人
   + 勉強会サークルの知り合い
   + SNSの知り合い
   + 趣味の知り合い
   + 家族
  }
  class 予算規模 {
   + ...
  }
  class 納期 {
   + 確定申告 3/15
   + マイナンバーカード たぶん今月届く
   + 新生活準備 1/31 (1/27(Wed)から有給)
  }
  class ビジネスモデル {
   + ...
  }
  class 環境 {
   + オタク趣味
   + - アニメ
   + - 蒐集
   + - 無形のものにお金を落とす
   + - 秋葉住み
   --
   + JetBrainsのライセンス
   + plantumlをリタルタイムにレンダリングできる環境
   --
   + 電子レンジ
   --
   + 養命酒
   --
   + 英字新聞の束
   --
  }

  class 競合 {
   + ...
  }
  class 外敵 {
   + ...
  }
  class 問題 {
   + 食パンがまずい
   + フレンチトーストがまずい
   + 流しが汚くなって料理が億劫
   + 朝起きたくない
   + 食事のメモが億劫
   + 養命酒飲むの忘れる
   + 書類の掃き溜めが溜まってる
   + 寝る前に腹が減る
   + 新生活の準備への不安
   + 勉強に時間かかりすぎ
  }
  note right of 問題::食パンがまずい
  家計の友だがまずすぎてきつい
  end note
  note right of 問題::朝起きたくない
  布団スマホの短縮に成功
  end note
  note right of 問題::食事のメモが億劫
  いつ死んでもおかしくない不健康な食事を脱し、健康的に太るために始めた
  不健康な食事を脱することはでき、最低限の目的は達した
  入力が面倒なのと、思うように太れていないので億劫になってきている
  end note
  note right of 問題::養命酒飲むの忘れる
  ビタミンは忘れないのになぜ？
  飲みたくないのでは
  end note
  note right of 問題::書類の掃き溜めが溜まってる
  したくないものあるが、
  視界に入らないので単に忘れてたのもある
  end note
  note right of 問題::寝る前に腹が減る
  そのままだと眠れないし朝起きるのもつらくなる
  食べすぎると胃がもたれて睡眠の質が心配
  end note
}

中間目的 --u[hidden]--> 勝利条件
施策 --u[hidden]--> 中間目的
廟算八要素 ---u[hidden]--> 施策

@enduml
