@startuml

title 人生

hide empty members
skinparam class {
  BackgroundColor<<deprecated>> Grey
  BackgroundColor<<done>> Cyan
  BackgroundColor<<new>> Yellow
}

left to right direction

package 勝利条件 {
  class 幸せに生きる
}

package 中間目的 {
  class 不安がない
  不安がない --> 幸せに生きる

  class キャリアの不安がない<<ref>>
  キャリアの不安がない --> 不安がない

  class お金の不安がない<<ref>>
  note bottom: 別プロジェクトへ切り出し
  お金の不安がない --> 不安がない

  class 新生活の準備の不安がない<<ref>>
  note bottom: 別プロジェクトへ切り出し
  新生活の準備の不安がない --> 不安がない

  class 自己虐待をしていない
  自己虐待をしていない --> 幸せに生きる

  class 他者との認識違いがない
  他者との認識違いがない --> 幸せに生きる

  class 健康である
  健康である --> 幸せに生きる
  class 筋骨隆々である
  筋骨隆々である --> 健康である

  class 億劫でないタスクのやり忘れがない
  億劫でないタスクのやり忘れがない --> 幸せに生きる

  class 睡眠の質がよい<<ref>>
  note bottom: 別プロジェクトへ移動
  睡眠の質がよい --> 幸せに生きる

  class 自己効力感が低くない
  自己効力感が低くない --> 幸せに生きる

  class 勉強に時間がかかりすぎない
  勉強に時間がかかりすぎない -> 自己効力感が低くない

  class 確定申告が億劫でない<<deprecated>>
  note bottom: 新生活プロジェクトへ移動
  class 仕訳が億劫でない<<deprecated>>
  仕訳が億劫でない --> 確定申告が億劫でない
}

package 施策 {
  class 自己虐待を見つけて改善する
  自己虐待を見つけて改善する --> 自己虐待をしていない

  class 人生をプ譜に書き留める
  人生をプ譜に書き留める --> 自己虐待を見つけて改善する

  class 自分の考えを相手が理解し相手の考えを自分が理解していることを確認する
  自分の考えを相手が理解し相手の考えを自分が理解していることを確認する --> 他者との認識違いがない

  class 自分の考えを自分が理解していることを確認する
  自分の考えを自分が理解していることを確認する --> 自己虐待をしていない

  class マインドセットをデスクトップ壁紙にしてつねに見えるようにする<<done>>
  マインドセットをデスクトップ壁紙にしてつねに見えるようにする --> 自分の考えを相手が理解し相手の考えを自分が理解していることを確認する
  マインドセットをデスクトップ壁紙にしてつねに見えるようにする --> 自分の考えを自分が理解していることを確認する

  class 健康的に太る
  健康的に太る --> 筋骨隆々である
  健康的に太る --> 健康である
  class 健康アプリで確立した食事をしばらく続ける
  note bottom
  次回の体重測定まで様子見
  サウナでしか体重を測れないのは辛い気もするが、継続的に測定・記入できる気もしない
  自動じゃないと絶対続かない
  end note
  健康アプリで確立した食事をしばらく続ける --> 健康的に太る

  class 新生活準備プロジェクトを発足する<<done>>
  新生活準備プロジェクトを発足する --> 新生活の準備の不安がない

  class 掃き溜め掃除の定期タスク化<<done>>
  掃き溜め掃除の定期タスク化 --> 億劫でないタスクのやり忘れがない

  class 養命酒の定期タスク化<<done>>
  note bottom: 効果あり。忘れずに飲めた
  養命酒の定期タスク化 --> 億劫でないタスクのやり忘れがない

  class 英字新聞の定期タスク化<<done>>
  英字新聞の定期タスク化 --> 億劫でないタスクのやり忘れがない

  class プロジェクト睡眠の質改善の発足<<done>>
  プロジェクト睡眠の質改善の発足 --> 睡眠の質がよい

  class ゆとりをもって勉強時間を見積もる<<new>>
  ゆとりをもって勉強時間を見積もる -> 勉強に時間がかかりすぎない
  class 3値見積もりをする<<new>>
  3値見積もりをする -> ゆとりをもって勉強時間を見積もる
  class 写経をやめる<<new>>
  写経をやめる -> 勉強に時間がかかりすぎない

  class 財政プロジェクト発足<<done>>
  財政プロジェクト発足 --> お金の不安がない

  class 仕訳を自動化する<<deprecated>>
  note bottom: 別プロジェクトへ移動
  仕訳を自動化する --> 仕訳が億劫でない

  class クレカのバックエンド口座を分ける<<deprecated>>
  note bottom: 別プロジェクトへ移動
  クレカのバックエンド口座を分ける --> 仕訳が億劫でない
}

package 廟算八要素 {
  class メンバー {
   + 自分
   + 個人事業の営業代行
   + アサイン先正社員
   + 友人
   + 勉強会サークルの知り合い
   + SNSの知り合い
   + 趣味の知り合い
   + 家族
  }
  class 予算規模 {
   + ...
  }
  class 納期 {
   + 確定申告 3/15
   + マイナンバーカード たぶん今月届く
   + 新生活準備 1/31 (1/27(Wed)から有給)
  }
  class ビジネスモデル {
   + ...
  }
  class 環境 {
   + オタク趣味
   + - アニメ
   + - 蒐集
   + - 無形のものにお金を落とす
   + - 秋葉住み
   --
   + JetBrainsのライセンス
   + plantumlをリタルタイムにレンダリングできる環境
   --
   + 電子レンジ
   --
   + 養命酒
   --
   + 英字新聞の束
   --
   + 確定申告
  }

  class 競合 {
   + ...
  }
  class 外敵 {
   + ...
  }
  class 問題 {
   + 食パンがまずい
   + フレンチトーストがまずい
   + 流しが汚くなって料理が億劫
   + 朝起きたくない
   + 書類の掃き溜めが溜まってる
   + 英字新聞溜まってる
   + 寝る前に腹が減る
   + 新生活の準備への不安
   + 勉強に時間かかりすぎ
  }
  note right of 問題::食パンがまずい
  家計の友だがまずすぎてきつい
  end note
  note right of 問題::フレンチトーストがまずい
  調理方法と調理器具に難がありそう
  end note
  note right of 問題::書類の掃き溜めが溜まってる
  したくないものあるが、
  視界に入らないので単に忘れてたのもある
  end note
  note right of 問題::lifeプロジェクトの編集に時間がかかっている
  もう少しやってるうちに収束するか？様子見
  end note
}

中間目的 --u[hidden]--> 勝利条件
施策 --u[hidden]--> 中間目的
廟算八要素 ---u[hidden]--> 施策

@enduml
