@startuml

title 人生

hide empty members
skinparam class {
  BackgroundColor<<deprecated>> Grey
  BackgroundColor<<done>> Cyan
  BackgroundColor<<new>> Yellow
}


package 勝利条件 {
  class 幸せに生きる
}

package 中間目的 {
  class 不安がない
  不安がない --> 幸せに生きる

  class キャリアの不安がない<<ref>> extends 不安がない
  class お金の不安がない extends 不安がない
  class 新生活の準備の不安がない<<new>> extends 不安がない

  class 自己虐待をしていない
  自己虐待をしていない --> 幸せに生きる

  class 他者との認識違いがない
  他者との認識違いがない --> 幸せに生きる

  class 健康である<<new>>
  class 筋骨隆々である<<new>>
  note bottom: まず体重が増えないと話にならない

  筋骨隆々である --> 健康である

  class 億劫でないタスクのやり忘れがない<<new>>

  class 睡眠の質がよい<<new>>

  class 自己効力感が低くない<<new>>
  class 勉強に時間がかかりすぎない<<new>>
  勉強に時間がかかりすぎない -> 自己効力感が低くない

  class 確定申告が億劫でない<<new>>
  class 仕訳が億劫でない<<new>>
  仕訳が億劫でない --> 確定申告が億劫でない
}

package 施策 {
  class 自己虐待を見つけて改善する
  自己虐待を見つけて改善する --> 自己虐待をしていない

  class 人生をプ譜に書き留める
  人生をプ譜に書き留める --> 自己虐待を見つけて改善する

  class 自分の考えを相手が理解し相手の考えを自分が理解していることを確認する
  自分の考えを相手が理解し相手の考えを自分が理解していることを確認する --> 他者との認識違いがない

  class 自分の考えを自分が理解していることを確認する
  自分の考えを自分が理解していることを確認する --> 自己虐待をしていない

  class マインドセットをデスクトップ壁紙にしてつねに見えるようにする<<new>>
  マインドセットをデスクトップ壁紙にしてつねに見えるようにする --> 自分の考えを相手が理解し相手の考えを自分が理解していることを確認する
  マインドセットをデスクトップ壁紙にしてつねに見えるようにする --> 自分の考えを自分が理解していることを確認する

  class 健康的に太る<<new>>
  健康的に太る --> 筋骨隆々である
  健康的に太る --> 健康である
  class 健康アプリで確立した食事をしばらく続ける<<new>>
  note bottom: アプリ入力は面倒なのでやらない
  健康アプリで確立した食事をしばらく続ける --> 健康的に太る

  class 新生活準備プロジェクトを発足する<<new>>
  新生活準備プロジェクトを発足する --> 新生活の準備の不安がない

  class 掃き溜め掃除の定期タスク化<<new>>
  掃き溜め掃除の定期タスク化 --> 億劫でないタスクのやり忘れがない
  class 養命酒の定期タスク化<<new>>
  養命酒の定期タスク化 --> 億劫でないタスクのやり忘れがない
  class 英字新聞の定期タスク化<<new>>
  英字新聞の定期タスク化 --> 億劫でないタスクのやり忘れがない

  class プロジェクト睡眠の質改善の発足<<new>>
  プロジェクト睡眠の質改善の発足 --> 睡眠の質がよい

  class ゆとりをもって勉強時間を見積もる<<new>>
  ゆとりをもって勉強時間を見積もる -> 勉強に時間がかかりすぎない
  class 3値見積もりをする<<new>>
  3値見積もりをする -> ゆとりをもって勉強時間を見積もる
  class 写経をやめる<<new>>
  写経をやめる -> 勉強に時間がかかりすぎない

  class 財政プロジェクト発足<<new>>
  財政プロジェクト発足 --> お金の不安がない

  class 仕訳を自動化する<<new>>
  仕訳を自動化する --> 仕訳が億劫でない
  class クレカのバックエンド口座を分ける<<new>>
  クレカのバックエンド口座を分ける --> 仕訳が億劫でない
}

package 廟算八要素 {
  class メンバー {
   + 自分
   + 個人事業の営業代行
   + アサイン先正社員
   + 友人
   + 勉強会サークルの知り合い
   + SNSの知り合い
   + 趣味の知り合い
   + 家族
  }
  class 予算規模 {
   + ...
  }
  class 納期 {
   + 確定申告 3/15
   + マイナンバーカード たぶん今月届く
   + 新生活準備 1/31 (1/27(Wed)から有給)
  }
  class ビジネスモデル {
   + ...
  }
  class 環境 {
   + オタク趣味
   + - アニメ
   + - 蒐集
   + - 無形のものにお金を落とす
   + - 秋葉住み
   --
   + JetBrainsのライセンス
   + plantumlをリタルタイムにレンダリングできる環境
   --
   + 電子レンジ
   --
   + 養命酒
   --
   + 英字新聞の束
   --
   + 確定申告
  }

  class 競合 {
   + ...
  }
  class 外敵 {
   + ...
  }
  class 問題 {
   + 食パンがまずい
   + フレンチトーストがまずい
   + 流しが汚くなって料理が億劫
   + 朝起きたくない
   + 養命酒飲むの忘れる
   + 書類の掃き溜めが溜まってる
   + 英字新聞溜まってる
   + 寝る前に腹が減る
   + 新生活の準備への不安
   + 勉強に時間かかりすぎ
   + 確定申告が億劫
  }
  note right of 問題::食パンがまずい
  家計の友だがまずすぎてきつい
  end note
  note right of 問題::朝起きたくない
  布団スマホの短縮に成功
  end note
  note right of 問題::養命酒飲むの忘れる
  ビタミンは忘れないのになぜ？
  -> 飲むタイミングが定まっておらず、かつ酒なので日中は飲めないから
  end note
  note right of 問題::書類の掃き溜めが溜まってる
  したくないものあるが、
  視界に入らないので単に忘れてたのもある
  end note
  note right of 問題::寝る前に腹が減る
  そのままだと眠れないし朝起きるのもつらくなる
  食べすぎると胃がもたれて睡眠の質が心配
  end note
  note right of 問題::確定申告が億劫
  とりわけ仕訳が億劫
  end note
}

中間目的 --u[hidden]--> 勝利条件
施策 --u[hidden]--> 中間目的
廟算八要素 ---u[hidden]--> 施策

@enduml
