@startuml

title 人生

hide empty members
skinparam class {
  BackgroundColor<<deprecated>> Grey
  BackgroundColor<<done>> Cyan
  BackgroundColor<<new>> Yellow
}

left to right direction

package 勝利条件 {
  class 幸せに生きる
}

package 中間目的 {
  class 不安がない
  不安がない --> 幸せに生きる

  class キャリアの不安がない<<ref>>
  キャリアの不安がない --> 不安がない

  class お金の不安がない<<ref>>
  お金の不安がない --> 不安がない

  class 新生活の準備の不安がない<<ref>>
  新生活の準備の不安がない --> 不安がない

  class 苦手なカラオケに誘われる不安がない<<ref>>
  苦手なカラオケに誘われる不安がない --> 不安がない

  class 自己虐待をしていない
  自己虐待をしていない --> 心身が健康である

  class 他者との認識違いがない
  他者との認識違いがない --> 幸せに生きる

  class 心身が健康である
  心身が健康である --> 幸せに生きる
  class 筋骨隆々である
  筋骨隆々である --> 心身が健康である

  class 億劫で着手できないタスクがない<<new>>
  億劫で着手できないタスクがない -> 自己虐待をしていない

  class 睡眠の質がよい<<ref>>
  睡眠の質がよい --> 心身が健康である

  class 自己効力感が低くない
  自己効力感が低くない --> 心身が健康である

  class 食事に時間がかかりすぎない<<new>>
  食事に時間がかかりすぎない -> 自己効力感が低くない

  class マイクロスケジュールを破らない<<new>>
  マイクロスケジュールを破らない -> 自己効力感が低くない

  class 知識が浅く狭いことに対する不安がない<<new>>
  note bottom
  世界の解像度が広がると「楽しい」と感じることに気づいたが
  狭いことへの「焦りや不安の解消」が嬉しいだけかもしれない。
  切り分け出来ていないがひとまず仮置
  end note
  知識が浅く狭いことに対する不安がない --> 不安がない
}

package 施策 {
  class 自己虐待を見つけて改善する
  自己虐待を見つけて改善する --> 自己虐待をしていない

  class 人生をプ譜に書き留める
  人生をプ譜に書き留める --> 自己虐待を見つけて改善する

  class 自分の考えを相手が理解し相手の考えを自分が理解していることを確認する
  自分の考えを相手が理解し相手の考えを自分が理解していることを確認する --> 他者との認識違いがない

  class 自分の考えを自分が理解していることを確認する
  自分の考えを自分が理解していることを確認する --> 自己虐待をしていない

  class 健康的に太る
  健康的に太る --> 筋骨隆々である
  健康的に太る --> 心身が健康である
  class 健康アプリで確立した食事をしばらく続ける
  健康アプリで確立した食事をしばらく続ける --> 健康的に太る
  class 自動で集計できる体重計買う<<new>>
  自動で集計できる体重計買う --> 健康的に太る

  class やらなくてよいことはやらない決断をする<<new>>
  やらなくてよいことはやらない決断をする --> 億劫で着手できないタスクがない
  class 億劫でなくする<<new>>
  億劫でなくする --> 億劫で着手できないタスクがない
  class なぜ億劫なのか分析する<<new>>
  なぜ億劫なのか分析する -> 億劫でなくする

  class マイクロスケジュールをしない<<new>>
  マイクロスケジュールをしない --> マイクロスケジュールを破らない

  class タイムキーパー導入する<<new>>
  note bottom
  作業に集中して視野が狭窄になり
  気づかぬ間に時間が過ぎていたり達成困難なペースになっていたりする
  end note
  タイムキーパー導入する --> マイクロスケジュールを破らない

  class org専用emacsを最前面に置く<<new>>
  note bottom
  他の作業をしていても隠れないようにする
  end note
  org専用emacsを最前面に置く --> マイクロスケジュールを破らない

  class おいしいものを食べる<<new>>
  おいしいものを食べる --> 食事に時間がかかりすぎない

  class お腹をすかせる<<new>>
  お腹をすかせる --> 食事に時間がかかりすぎない

  class 3食規則正しくバランス良くとる<<new>>
  3食規則正しくバランス良くとる -> お腹をすかせる

  class ボイトレをする<<new>>
  ボイトレをする --> 苦手なカラオケに誘われる不安がない

  class はちみつを飲む<<new>>
  はちみつを飲む -> ボイトレをする
}

package 廟算八要素 {
  class メンバー {
   + 自分
   + 個人事業の営業代行
   + アサイン先正社員
   + 友人
   + 勉強会サークルの知り合い
   + SNSの知り合い
   + 趣味の知り合い
   + 家族
  }
  class 予算規模 {
   + ...
  }
  class 納期 {
   + 確定申告 3/15
   + マイナンバーカードはがき 1末〜2末に届くはず
   + 新生活準備 1/31 (1/27(Wed)から有給)
   ---
   + 食事時間 だいたい1h
  }
  class ビジネスモデル {
   + ...
  }
  class 環境 {
   + オタク趣味
   + - アニメ
   + - 蒐集
   + - 無形のものにお金を落とす
   + - 秋葉住み
   --
   + JetBrainsのライセンス
   + plantumlをリタルタイムにレンダリングできる環境
   --
   + 電子レンジ
   --
   + 養命酒
   --
   + 英字新聞の束
   --
   + 確定申告
   -- 食事時間 --
   + 朝: 1h程度(洗顔、調理、食事、洗い物、歯磨き、食休み)
  }

  class 競合 {
   + ...
  }
  class 外敵 {
   + ...
  }
  class 問題 {
   + ~流しが汚くなって料理が億劫
   + ~書類の掃き溜めが溜まってる
   + 英字新聞溜まってる
   + 新生活の準備への不安
   + プ譜の編集に時間がかかっている
   + マイクロスケジュール通りに作業が進まない
  }
  note right of 問題::~流しが汚くなって料理が億劫
  フライパンを新調し、洗う前に念入りに拭くようにして改善
  end note
  note right of 問題::~書類の掃き溜めが溜まってる
  定期タスク化して毎朝少しずつ倒して改善
  end note
}

中間目的 --u[hidden]--> 勝利条件
施策 --u[hidden]--> 中間目的
廟算八要素 ---u[hidden]--> 施策

@enduml
