@startuml

title キャリア形成

hide empty members
skinparam class {
  BackgroundColor<<deprecated>> Grey
  BackgroundColor<<done>> Cyan
  BackgroundColor<<new>> Yellow
}

left to right direction

package 勝利条件 {
  class キャリアの不安を感じない
}
package 中間目的 {
  class 経歴にPG以外を書くことができる
  経歴にPG以外を書くことができる --> キャリアの不安を感じない

  class PG以外の仕事の実績がある
  PG以外の仕事の実績がある -> 経歴にPG以外を書くことができる

  class PG以外の仕事の遂行能力がある
  PG以外の仕事の遂行能力がある -> PG以外の仕事の実績がある

  class 当座のVue3案件で不安を感じない<<deprecated>>
  note bottom
  経験あるし大丈夫でしょう多分

  どれくらいを求められているかもわからないし
  本来金もらってやるべきことだし
  end note
  当座のVue3案件で不安を感じない --> キャリアの不安を感じない
}

package 施策 {
  プロジェクトマネジメント能力をつける --> PG以外の仕事の遂行能力がある
  日常的にプ譜を書く -> プロジェクトマネジメント能力をつける

  要求分析_要件定義能力をつける --> PG以外の仕事の遂行能力がある
  ICONIXプロセス学ぶ -> 要求分析_要件定義能力をつける

  PG以外の業務経験を積める案件にジョインする --> PG以外の仕事の実績がある

  資格取得 --> PG以外の仕事の遂行能力がある
  JSTQB試験を受ける -> 資格取得
  IPA高度試験を受ける -> 資格取得

  class テスト技術者的側面で経歴書を更新する<<new>>
  テスト技術者的側面で経歴書を更新する --> PG以外の仕事の実績がある

  class シフトレフトやW字モデルを推進している案件にジョインする<<new>>
  シフトレフトやW字モデルを推進している案件にジョインする -> PG以外の業務経験を積める案件にジョインする

  class Vue3のチュートリアル一通りやる<<deprecated>>
  Vue3のチュートリアル一通りやる --> 当座のVue3案件で不安を感じない
}

package 廟算八要素 {
  class メンバー {
   + 自分
   + 個人事業の営業代行
   + アサイン先正社員
   + 友人
   + 勉強会サークルの知り合い
   + SNSの知り合い
  }
  class 予算規模 {
   + 年600程度の売上
   + JetBrains製品のライセンスが年間3万円くらい
  }
  class 納期 {
   + JSTQB試験:2/13
   + IPA試験:4/18
   + IPA試験申込:2/8
  }
  class ビジネスモデル {
   + 個人事業主
   + PGの業務委託
   + 準委任契約。時間を売っている
  }
  class 環境 {
   + Weeyble
   --
   + コロナ禍
   + オンライン勉強会等の増加
   + オンライン資格試験
   + フルリモートワーク
   + それにともなう通勤時間の排除
   --
   + 経験がそれほどないフロントエンド案件への不安
   --
   + 自作Gatsbyブログ
   --
   + JetBrains製品のライセンス
  }
  class 競合 {
   + 若者
   + 経歴が強そうな人材
  }
  class 外敵 {
   + ...
  }
  class スキル<<new>> {
   + テスト技術者的なマインドセット
   + ユーザーストーリーのリファインメント
  }
}


中間目的 --u[hidden]--> 勝利条件
施策 --u[hidden]--> 中間目的
廟算八要素 ---u[hidden]--> 施策

@enduml
