@startuml

title 2021新生活

hide empty members
skinparam class {
  BackgroundColor<<deprecated>> Grey
  BackgroundColor<<done>> Cyan
  BackgroundColor<<new>> Yellow
}

left to right direction


package 勝利条件 {
  class 円滑に新しい仕事を始められる
}

package 中間目的 {
  class 事務作業が済んでいる
  事務作業が済んでいる --> 円滑に新しい仕事を始められる
  class 開業完了
  開業完了 --> 事務作業が済んでいる
  class 青色申告申請完了
  青色申告申請完了 --> 事務作業が済んでいる
  class 仕訳が億劫でない
  仕訳が億劫でない .> 青色申告申請完了:<<前提>>
  class 保険の移行完了
  保険の移行完了 --> 事務作業が済んでいる
  class 運転免許証の住所変更完了
  運転免許証の住所変更完了 --> 事務作業が済んでいる
  class 2020確定申告完了
  2020確定申告完了 --> 事務作業が済んでいる
}

package 施策 {
  class 開業届を出す
  開業届を出す --> 開業完了
  class 青色申請する
  青色申請する --> 開業完了
  仕訳の多くを自動化する-> 仕訳が億劫でない
  事業用クレカを分ける --> 仕訳の多くを自動化する
  事業用口座を事業用クレカに紐付ける --> 仕訳の多くを自動化する
  事業用クレカを分ける -> 事業用口座を事業用クレカに紐付ける

  class 保険どうするか決める
  保険どうするか決める --> 保険の移行完了
  class 運転免許証の住所変更
  運転免許証の住所変更 --> 運転免許証の住所変更完了

  仕訳する -> 2020確定申告完了
  2020年1月から3月の決済の資料請求する -> 仕訳する
  マイナンバーカードの証明書取得する -> 2020確定申告完了
  マイナンバーカードのカードリーダー調達する -> 2020確定申告完了
}

package 廟算八要素 {
  class メンバー {
   + 自分
  }
  class 予算規模 {
   + ...
  }
  class 納期 {
   + 仕事1/26まで
   + 平日休み1/29まで
   + 新生活前 2/1まで
  }
  class ビジネスモデル {
   + ...
  }
  class 環境 {
   + コロナ禍
   + それにともなう窓口時短、閉鎖等
   --
   + 確定申告
   --
   + freeeによる確定申告実績
   --
   + e-Tax簡易申請はもうできない
  }

  class 競合 {
   + ...
  }
  class 外敵 {
   + ...
  }
  class 問題 {
   + 確定申告が億劫
  }
  note right of 問題::確定申告が億劫
  とりわけ仕訳が億劫
  end note
}

中間目的 --u[hidden]--> 勝利条件
施策 --u[hidden]--> 中間目的
廟算八要素 ---u[hidden]--> 施策

@enduml
